name: security_camera_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # ONVIF discovery and video streaming
  easy_onvif: ^3.1.2
  fvp: ^0.33.1
  video_player: ^2.9.2
  chewie: ^1.8.5
  shared_preferences: ^2.3.3
  crypto: ^3.0.3
  dio: ^5.4.0
  xml: ^6.4.2
  path: ^1.8.3
  path_provider: ^2.1.5
  http_auth: ^1.0.3
  http: ^1.2.2
  sdp_transform: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
